# Generated by Django 5.0.14 on 2025-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('sales', models.IntegerField()),
                ('product', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'sales_data',
                'indexes': [models.Index(fields=['day'], name='sales_data_day_880b07_idx'), models.Index(fields=['product'], name='sales_data_product_f56b39_idx')],
            },
        ),
    ]
